import { CardDef } from './types';

export const CARDS_DATA: CardDef[] = [
  // ==========================================
  // SOLAR / PYRE FACTION
  // ==========================================
  {
    id: 'sol_initiate',
    name: 'Solar Spark Drake',
    element: 'solar',
    form: 1,
    type: 'creature',
    cost: 1,
    atk: 2,
    hp: 2,
    rarity: 'common',
    art: '/assets/cards/card_ignis.jpg',
    cropOffset: 'center 10%',
    keywords: [],
    desc: 'Battlecry: Deal 1 damage to the lowest health enemy unit or Vanguard.',
    lore: 'Born in the heart of solar flares, it hungers for cosmic fuel.'
  },
  {
    id: 'sol_paladin',
    name: 'Pyre Vanguard',
    element: 'solar',
    form: 2,
    ascendsFrom: 'solar',
    type: 'creature',
    cost: 4,
    atk: 4,
    hp: 4,
    rarity: 'rare',
    art: '/assets/cards/card_pyre_vanguard.jpg',
    cropOffset: 'center 20%',
    keywords: ['Aegis'],
    hasAegis: true,
    desc: 'Aegis (Immune to next damage). Ascension: Gain +2 ATK.',
    lore: 'Golden clad warriors wielding shields forged from dying supernovas.'
  },
  {
    id: 'ignis_apex',
    name: 'Ignis, Astral Sovereign',
    element: 'solar',
    form: 3,
    ascendsFrom: 'solar',
    type: 'creature',
    cost: 7,
    atk: 8,
    hp: 8,
    rarity: 'legendary',
    art: '/assets/cards/card_ignis.jpg',
    cropOffset: 'center 20%',
    keywords: ['Rush'],
    canAttackOnSummon: true,
    desc: 'Rush. Ascension Burst: Deal 3 damage to all enemy units on the battlefield.',
    lore: 'The celestial dragon whose heartbeat ignites stars across the cosmos.'
  },
  {
    id: 'spell_solar_lance',
    name: 'Solar Lance',
    element: 'solar',
    type: 'spell',
    cost: 2,
    rarity: 'common',
    art: '/assets/cards/spell_solar_lance.jpg',
    cropOffset: 'center 30%',
    desc: 'Deal 3 damage to target enemy creature or enemy Vanguard directly.',
    lore: 'A concentrated beam of stellar plasma piercing through armor.',
    targetType: 'any_enemy'
  },
  {
    id: 'ward_sunfire_retribution',
    name: 'Sunfire Sigil',
    element: 'solar',
    type: 'ward',
    cost: 2,
    rarity: 'epic',
    art: '/assets/cards/ward_sunfire_sigil.jpg',
    cropOffset: 'center 25%',
    desc: 'Secret Ward: When your Vanguard is attacked, deal 4 retaliatory damage to the attacker.',
    lore: 'A hidden solar rune that retaliates with blinding stellar retribution.',
    trigger: 'on_vanguard_attacked'
  },

  // ==========================================
  // VOID / SHADOW FACTION
  // ==========================================
  {
    id: 'void_stalker',
    name: 'Voidling Assassin',
    element: 'void',
    form: 1,
    type: 'creature',
    cost: 2,
    atk: 3,
    hp: 2,
    rarity: 'common',
    art: '/assets/cards/card_valkyrie.jpg',
    cropOffset: 'center 45%',
    keywords: ['Stealth', 'Deathrattle'],
    desc: 'Deathrattle: Draw 1 card from your deck when destroyed.',
    lore: 'Skulks in the spaces between realities, waiting for a heartbeat.'
  },
  {
    id: 'nyx_valkyrie',
    name: 'Nyx, Eclipse Valkyrie',
    element: 'void',
    form: 2,
    ascendsFrom: 'void',
    type: 'creature',
    cost: 5,
    atk: 5,
    hp: 4,
    rarity: 'epic',
    art: '/assets/cards/card_valkyrie.jpg',
    cropOffset: 'center 20%',
    keywords: ['Rush', 'Lifesteal'],
    canAttackOnSummon: true,
    lifesteal: true,
    desc: 'Rush. Lifesteal (Heals your Vanguard for damage dealt). Ascension: Gain +2 HP.',
    lore: 'A fallen seraph who dances through eclipse skies, harvesting mortal souls.'
  },
  {
    id: 'void_reaper_apex',
    name: 'Obsidian Dreadlord',
    element: 'void',
    form: 3,
    ascendsFrom: 'void',
    type: 'creature',
    cost: 8,
    atk: 7,
    hp: 9,
    rarity: 'legendary',
    art: '/assets/cards/card_valkyrie.jpg',
    cropOffset: 'center 15%',
    keywords: ['Lifesteal'],
    lifesteal: true,
    desc: 'Ascension Burst: Instantly destroy the lowest health enemy creature.',
    lore: 'Master of the event horizon, dragging all light and hope into oblivion.'
  },
  {
    id: 'spell_void_drain',
    name: 'Essence Drain',
    element: 'void',
    type: 'spell',
    cost: 3,
    rarity: 'rare',
    art: '/assets/cards/card_valkyrie.jpg',
    cropOffset: 'center 60%',
    desc: 'Deal 3 damage to an enemy unit. Restore 3 HP to your Vanguard Champion.',
    lore: 'Siphons life essence directly into the dark crucible of the void.',
    targetType: 'enemy_unit'
  },
  {
    id: 'ward_shadow_rift',
    name: 'Shadow Mirror Ward',
    element: 'void',
    type: 'ward',
    cost: 2,
    rarity: 'rare',
    art: '/assets/cards/card_valkyrie.jpg',
    cropOffset: 'center 35%',
    desc: 'Secret Ward: When an opponent Ascends a Form II or Form III creature, reduce its ATK to 1.',
    lore: 'The void absorbs and corrupts the greatest strength of any titan.',
    trigger: 'on_enemy_ascend'
  },

  // ==========================================
  // VERDANT / NATURE FACTION
  // ==========================================
  {
    id: 'verdant_sprout',
    name: 'Moss Sprite',
    element: 'verdant',
    form: 1,
    type: 'creature',
    cost: 1,
    atk: 1,
    hp: 3,
    rarity: 'common',
    art: '/assets/cards/card_titan.jpg',
    cropOffset: 'center 60%',
    keywords: ['Taunt'],
    hasTaunt: true,
    desc: 'Taunt (Enemies must attack this guardian unit first).',
    lore: 'A friendly guardian sprout with bark as tough as ancient ironwood.'
  },
  {
    id: 'yggdrasil_titan',
    name: 'Yggdrasil Ancient',
    element: 'verdant',
    form: 2,
    ascendsFrom: 'verdant',
    type: 'creature',
    cost: 6,
    atk: 4,
    hp: 8,
    rarity: 'legendary',
    art: '/assets/cards/card_titan.jpg',
    cropOffset: 'center 20%',
    keywords: ['Taunt', 'Regen'],
    hasTaunt: true,
    desc: 'Taunt. Ascension Burst: Restore 4 HP to your Vanguard and all friendly creatures.',
    lore: 'Awakened from millennial slumber to shield the sacred groves from destruction.'
  },
  {
    id: 'verdant_hydra_apex',
    name: 'Colossus of the Bloom',
    element: 'verdant',
    form: 3,
    ascendsFrom: 'verdant',
    type: 'creature',
    cost: 7,
    atk: 8,
    hp: 10,
    rarity: 'epic',
    art: '/assets/cards/card_titan.jpg',
    cropOffset: 'center 10%',
    keywords: ['Overpower'],
    desc: 'Ascension Burst: Permanently gain +1 Maximum Mana Flow capacity.',
    lore: 'Its roots delve into the molten heart of the earth, feeding on primal ley lines.'
  },
  {
    id: 'spell_feral_surge',
    name: 'Primal Overgrowth',
    element: 'verdant',
    type: 'spell',
    cost: 2,
    rarity: 'common',
    art: '/assets/cards/card_titan.jpg',
    cropOffset: 'center 40%',
    desc: 'Grant a friendly creature +2 ATK and +3 HP.',
    lore: 'Infuses blood and wood with wild celestial chloroplast energy.',
    targetType: 'friendly_unit'
  },
  {
    id: 'ward_briar_trap',
    name: 'Thornsnare Ward',
    element: 'verdant',
    type: 'ward',
    cost: 2,
    rarity: 'common',
    art: '/assets/cards/card_titan.jpg',
    cropOffset: 'center 30%',
    desc: 'Secret Ward: When an enemy declares an attack, destroy it if it has 3 or less HP.',
    lore: 'Razor thorns burst from the earth at the first tremor of an invading step.',
    trigger: 'on_creature_attack'
  },

  // ==========================================
  // TIDE / WATER FACTION
  // ==========================================
  {
    id: 'tide_siren_initiate',
    name: 'Coral Nymph',
    element: 'tide',
    form: 1,
    type: 'creature',
    cost: 2,
    atk: 2,
    hp: 3,
    rarity: 'common',
    art: '/assets/cards/card_tide.jpg',
    cropOffset: 'center 60%',
    keywords: ['Freeze'],
    desc: 'Battlecry: Freeze target enemy creature for 1 turn (cannot attack next turn).',
    lore: 'Sings an enchanting melody that chills blood and stops swords in mid-air.'
  },
  {
    id: 'tethys_tide_weaver',
    name: 'Tethys, Tide Weaver',
    element: 'tide',
    form: 2,
    ascendsFrom: 'tide',
    type: 'creature',
    cost: 5,
    atk: 4,
    hp: 6,
    rarity: 'legendary',
    art: '/assets/cards/card_tide.jpg',
    cropOffset: 'center 20%',
    keywords: ['Freeze'],
    desc: 'Ascension Burst: Draw 2 cards and Freeze all enemy units on the battlefield for 1 turn.',
    lore: 'Empress of the Abyssal Trenches, commanding unstoppable tides of mystic liquid.'
  },
  {
    id: 'kraken_apex',
    name: 'Leviathan of the Depths',
    element: 'tide',
    form: 3,
    ascendsFrom: 'tide',
    type: 'creature',
    cost: 8,
    atk: 9,
    hp: 9,
    rarity: 'epic',
    art: '/assets/cards/card_tide.jpg',
    cropOffset: 'center 10%',
    keywords: ['Overpower'],
    desc: 'Ascension: Return 1 non-Apex enemy creature back to its owner’s hand.',
    lore: 'The entire ocean trembles when this ancient sovereign awakens from the abyss.'
  },
  {
    id: 'spell_tidal_wave',
    name: 'Abyssal Deluge',
    element: 'tide',
    type: 'spell',
    cost: 4,
    rarity: 'rare',
    art: '/assets/cards/card_tide.jpg',
    cropOffset: 'center 40%',
    desc: 'Deal 2 damage to all enemy units and freeze them for 1 turn.',
    lore: 'A towering tsunami infused with arctic frost sweeping across the arena.'
  },
  {
    id: 'ward_frozen_tide',
    name: 'Glacial Stasis Ward',
    element: 'tide',
    type: 'ward',
    cost: 2,
    rarity: 'rare',
    art: '/assets/cards/card_tide.jpg',
    cropOffset: 'center 30%',
    desc: 'Secret Ward: When an enemy declares a direct attack on your Vanguard, negate the attack and freeze the attacker.',
    lore: 'Instant permafrost turns incoming lethal strikes to brittle ice crystals.',
    trigger: 'on_direct_attack'
  },

  // ==========================================
  // ASTRAL / CHRONO FACTION
  // ==========================================
  {
    id: 'aurelius_chronomancer',
    name: 'Aurelius, Chronomancer',
    element: 'astral',
    form: 1,
    type: 'creature',
    cost: 3,
    atk: 2,
    hp: 4,
    rarity: 'legendary',
    art: '/assets/cards/card_time.jpg',
    cropOffset: 'center 20%',
    keywords: ['Resonance'],
    desc: 'Battlecry: Reduce the Mana cost of all cards in your hand by 1 (minimum 0).',
    lore: 'Unravels threads of time to weave tomorrow into today.'
  },
  {
    id: 'astral_seer',
    name: 'Starweaver Adept',
    element: 'astral',
    form: 2,
    ascendsFrom: 'astral',
    type: 'creature',
    cost: 4,
    atk: 3,
    hp: 5,
    rarity: 'rare',
    art: '/assets/cards/card_time.jpg',
    cropOffset: 'center 45%',
    keywords: [],
    desc: 'Ascension Burst: Discover 1 random high-tier Apex or Legendary card into your hand.',
    lore: 'Channels cosmic stardust into crystalline prophecies of destiny.'
  },
  {
    id: 'astral_chronos_apex',
    name: 'Chronos, Lord of Eternity',
    element: 'astral',
    form: 3,
    ascendsFrom: 'astral',
    type: 'creature',
    cost: 9,
    atk: 10,
    hp: 10,
    rarity: 'legendary',
    art: '/assets/cards/card_time.jpg',
    cropOffset: 'center 10%',
    keywords: ['Rush', 'Aegis'],
    canAttackOnSummon: true,
    hasAegis: true,
    desc: 'Rush. Aegis. Ascension: Take an extra turn immediately after this one!',
    lore: 'The ultimate architect of the cosmic timeline who bends eternity to his will.'
  },
  {
    id: 'spell_temporal_rewind',
    name: 'Chronoshift',
    element: 'astral',
    type: 'spell',
    cost: 3,
    rarity: 'epic',
    art: '/assets/cards/card_time.jpg',
    cropOffset: 'center 60%',
    desc: 'Heal your Vanguard for 6 HP and draw 1 card.',
    lore: 'Reverses localized entropy to mend mortal wounds before they ever landed.'
  },
  {
    id: 'ward_astral_rift',
    name: 'Continuum Collapse Ward',
    element: 'astral',
    type: 'ward',
    cost: 2,
    rarity: 'epic',
    art: '/assets/cards/card_time.jpg',
    cropOffset: 'center 35%',
    desc: 'Secret Ward: When your Vanguard would take fatal lethal damage, survive with 1 HP and draw 2 emergency cards.',
    lore: 'Rewinds time at the brink of death to rewrite fate itself.',
    trigger: 'on_lethal_damage'
  }
];
