export const GAME_TITLES = [
  'TCG Turbo',
  'TCG Turbo: Rift of Runes',
  'TCG Turbo: Shattered Echoes',
  'Aetherbound: Rift of Runes',
  'Conduit: Shattered Echoes',
  'Resonants: The Astral Spark',
  'Prismfall: Sovereign Tides',
  'Vanguard Continuum',
  'Grimoire Eclipse',
  'Sigilforge: Clash of Spheres',
  'Astral Ascendants',
  'Chroma Shard: Realm of Titans',
  'Aethelgard: The Living Loom',
  'Runic Horizon',
  'Soulbound Conduits',
  'Nexus Pulse: Battle of the Spheres',
  'Veilbreaker: Sovereign Sparks',
  'Aura Clash: Chronicles of Eden',
  'Arcane Flux: The Prime Wardens',
  'Voidweave: Celestial Duel',
  'Ethereal Gambit: Realm of Shards',
  'Novabound: Astral Tides',
  'Runekind: Clash of the Ascended'
];
